export const VALID_EXPIRATIONS = [3600, 86400, 604800];
export const MAX_SECRET_LENGTH = process.env.NEXT_PUBLIC_MAX_SECRET_LENGTH
  ? +process.env.MAX_SECRET_LENGTH
  : 1024 * 1024 * 1000;

export const MAX_FILE_LENGTH = process.env.NEXT_PUBLIC_MAX_FILE_LENGTH
  ? +process.env.MAX_SECRET_LENGTH
  : MAX_SECRET_LENGTH;
